#!/bin/sh
#Author: Dimitri Tarasowski

PROCESS_DIR_MAIN=./inputs/Udacity_AZDIAS_Subset.csv
PROCESS_DIR_FEAT=./inputs/AZDIAS_Feature_Summary.csv
PROCESS_SAVE_PATH=./models/df.pkl

TRAIN_DATA_PATH=./models/df.pkl
TRAIN_SAVE_PATH=./models/model.pkl
TRAIN_SAVE_PCA=./models/X_pca.pkl

PREDICT_MODEL_PATH=./models/model.pkl
PREDICT_PCA_PATH=./models/X_pca.pkl


if [[ "$1" == "preprocess" ]]
then 
    echo "Running: $1"
    ENV=PREPROCESS python3 ./src/main.py $PROCESS_DIR_MAIN $PROCESS_DIR_FEAT $PROCESS_SAVE_PATH
fi

if [[ "$1" == "train" ]]
then 
    echo "Running: $1"
    ENV=TRAIN python3 ./src/main.py $TRAIN_DATA_PATH $TRAIN_SAVE_PATH $TRAIN_SAVE_PCA --pca_components 116 --n_clusters 19
fi

if [[ "$1" == "predict" ]]
then 
    echo "Running: $1"
    ENV=PREDICT python3 ./src/main.py $PREDICT_MODEL_PATH $PREDICT_PCA_PATH 
fi
